### ISSUE TITLE
'NSAttributedString' initializer is inaccessible

### ISSUE THREAD

**Issue by rboschjr** [prolificinteractive/Marker#25]
Thanks for creating and sharing this library -- I'm happy to not have to roll my own markdown formatting!

I'm a relative Swift n00b, so I'm not sure if this is an actual issue or if I'm doing something wrong...

I've pulled down Marker (v1.1.0) using CocoaPods and am trying to use the NSAttributedString initializer extension to create an attributed string like so:

```
            let contents = NSAttributedString(string: entry,
                                              textStyle: textStyle)
```

And the build fails with the following error:

_'NSAttributedString' initializer is inaccessible due to 'internal' protection level_

Adding 'public' to the initializer in NSAttributedString+Extensions.swift does the trick:

```
    public convenience init(string: String, textStyle: TextStyle) {
```
I wanted to confirm whether this is the correct fix, and if so to see if it can be rolled into the next release. Or, if the library is correct and I'm using it improperly, that'd be great to know as well.

Thanks,
Robert

**Comment by htinlinn** [comment]
Hey Robert, you should be able to use the public functions in `Marker.swift` for this purpose: https://github.com/prolificinteractive/Marker/blob/master/Marker/Marker/Marker.swift

**Comment by rboschjr** [comment]
Got it -- thanks for the pointer, and sorry for the noise!
