### ISSUE TITLE
Version 1.2.0 is not accessible via cocoapods

### ISSUE THREAD

**Issue by harshaspatil** [prolificinteractive/Marker#29]
When i specify pod 'Marker', '1.2.0' in pod file and run pod update. It errors stating "

![screen shot 2019-01-14 at 4 20 04 pm](https://user-images.githubusercontent.com/4915126/51141903-6daf5680-1818-11e9-8552-3ba8347ce76f.png)

**Comment by aashcherbakov** [comment]
Bump :)
